"""
Prompt templates for T-MCTS.

All templates use %{PLACEHOLDER} format, replaced at runtime via str.replace().
"""

_SYSTEM = (
    "You are a tool-integrated symbolic reasoning assistant.\n"
    "\n"
    "You solve logical and symbolic reasoning problems by applying "
    "one or more of the following tools:\n"
    "- prover9: first-order logic entailment and theorem proving "
    "(FOL format).\n"
    "- pyke: rule-based inference over facts and rules "
    "(Datalog syntax).\n"
    "- z3: constraint solving, satisfiability, ordering, scheduling, "
    "and assignment (SMT-LIB2 format).\n"
    "- minizinc: finite-domain constraint solving, enumeration, and "
    "counting (MiniZinc language).\n"
    "\n"
    "You will receive the problem and options once at the beginning.\n"
    "In later turns, use the conversation history instead of asking "
    "for repeated information.\n"
    "\n"
    "Briefly explain your reasoning before each decision, "
    "then end with the required tag.\n"
    "Use tools to solve the problem. Do not guess.\n"
    "The answer must be one of the given options.\n"
    "You may switch tools if the current one is not suitable.\n"
    "\n"
    "OUTPUT FORMAT — EVERY response must end with exactly ONE of:\n"
    "\n"
    "  <tool_call>\n"
    '  {"name": "TOOL", "arguments": {"code": "..."}}\n'
    "  </tool_call>\n"
    "\n"
    "  <answer>\n"
    "  ... your full answer ...\n"
    "  </answer>\n"
    "\n"
    "RULES:\n"
    "- The tool_call must be valid JSON — double-quoted keys and strings.\n"
    "- The arguments.code field contains your executable code.\n"
    "- Never use markdown code blocks (```) for your code.\n"
    "- Never place text AFTER the closing tag.\n"
    "- The closing tag must be the very last thing in your response.\n"
)

_TASK_INPUT = (
    "Solve the following symbolic reasoning problem.\n"
    "\n"
    "%{CONTEXT_BLOCK}"
    "Question:\n"
    "%{QUESTION}\n"
    "\n"
    "Options:\n"
    "%{OPTIONS}\n"
)

_TOOL_CODE_GENERATION = (
    "Select the most suitable tool and generate executable code.\n"
    "\n"
    "Available tools:\n"
    "\n"
    "%{TOOL_FORMAT_HINTS}"
    "\n"
    "Requirements:\n"
    "- Choose the best tool for this problem.\n"
    "- Generate self-contained code in the tool's native format.\n"
    "- The code should produce output that determines the final answer.\n"
    "- Do not directly guess the final answer.\n"
    "\n"
    "Briefly explain the formalization in <think> tags before the code.\n"
    "End your response with:\n"
    "\n"
    "<think>\n"
    "... your reasoning ...\n"
    "</think>\n"
    "<tool_call>\n"
    '{"name": "TOOL_NAME", "arguments": {"code": "... your code ..."}}\n'
    "</tool_call>\n"
    "\n"
    "IMPORTANT: Do NOT use markdown code blocks (```).  "
    "The tool_call must be valid JSON.  "
    "Do NOT add text after </tool_call>.  After </tool_call> there must be NOTHING else.  "
    "</tool_call> must be the last line of your response.\n"
)

_TOOL_CODE_REPAIR = (
    "The previous tool execution failed.\n"
    "\n"
    "<tool_response>\n"
    "%{ERROR_OUTPUT}\n"
    "</tool_response>\n"
    "\n"
    "Repair the previous code based on the error message above.\n"
    "\n"
    "Requirements:\n"
    "- Keep the same tool.\n"
    "- Fix the code according to the error message.\n"
    "- The repaired code must be executable.\n"
    "- The code should print enough information to determine the final answer.\n"
    "- Do not change the problem or options.\n"
    "\n"
    "%{TOOL_HINT}\n"
    "\n"
    "Briefly explain the cause of the error in <think> tags.\n"
    "End your response with:\n"
    "\n"
    "<think>\n"
    "... your analysis of the error ...\n"
    "</think>\n"
    "<tool_call>\n"
    '{"name": "TOOL_NAME", "arguments": {"code": "... your repaired code ..."}}\n'
    "</tool_call>\n"
    "\n"
    "IMPORTANT: Do NOT use markdown code blocks (```).  "
    "The tool_call must be valid JSON.  "
    "Do NOT add text after </tool_call>.  After </tool_call> there must be NOTHING else.  "
    "</tool_call> must be the last line of your response.\n"
)

_RESULT_INTERPRETATION = (
    "Based on the latest tool output:\n"
    "\n"
    "<tool_response>\n"
    "%{TOOL_OUTPUT}\n"
    "</tool_response>\n"
    "\n"
    "Choose one of:\n"
    "\n"
    "A) Sufficient information to answer.\n"
    "   Briefly explain your reasoning.  Wrap your explanation in\n"
    "   <think> tags, and place your answer in <answer> tags.\n"
    "   Your <answer> should contain a concise summary of the\n"
    "   complete solution — what the problem asked, what tool and\n"
    "   formalisation you used, what the tool produced, and why it\n"
    "   leads to your chosen option.  ALWAYS end the answer with:\n"
    '   "The final answer is X" where X is A, B, C, D, or E.\n'
    "   End your response with:\n"
    "   <think>\n"
    "   ... your analysis of the tool output ...\n"
    "   </think>\n"
    "   <answer>\n"
    "   ... your solution summary ...\n"
    "   The final answer is X\n"
    "   </answer>\n"
    "\n"
    "B) Further analysis is needed — write another tool call.\n"
    "   You may switch to a different tool if needed.\n"
    "   Briefly explain your reasoning in <think> tags.\n"
    "   End your response with:\n"
    "   <think>\n"
    "   ... your reasoning ...\n"
    "   </think>\n"
    "   <tool_call>\n"
    '   {"name": "TOOL_NAME", "arguments": {"code": "..."}}\n'
    "   </tool_call>\n"
    "\n"
    "Requirements:\n"
    "- If continuing, the new code must be based on the latest observation.\n"
    "- If the latest observation is an error, try a different approach "
    "or switch tools.\n"
    "- Do not output an answer outside the given options.\n"
    "- Do not introduce unsupported claims.\n"
    "\n"
    "IMPORTANT: Do NOT use markdown code blocks (```).  "
    "Do NOT add text after the closing tag.  "
    "The closing tag must be the last line of your response.\n"
)

PROMPTS = {
    "SYMBOLIC_REASONING_SYSTEM": _SYSTEM,
    "TASK_INPUT": _TASK_INPUT,
    "TOOL_CODE_GENERATION": _TOOL_CODE_GENERATION,
    "TOOL_CODE_REPAIR": _TOOL_CODE_REPAIR,
    "RESULT_INTERPRETATION": _RESULT_INTERPRETATION,
}
